- travis: TeamMacLean/geefu.io
  dir: /opt/geefu.io
  action:
    - echo "test 1"
    - echo "test 2"
- travis: TeamMacLean/dataHog
  dir: /opt/datahog
  action:
    - echo "test 1"
    - echo "test 2"