- travis: TeamMacLean/geefu.io
  dir: /opt/geefu.io
  action:
    - git pull
    - pm2 restart geefu.io
- travis: TeamMacLean/dataHog
  dir: /opt/datahog
  action:
    - git pull
    - pm2 restart datahog